lint:
  template_strings:
    - assets/workflow_FLARE/Snakefile
nf_core_version: 4.0.2
repository_type: pipeline
template:
  author: Aravind Sundaravadivelu
  description: A pipeline to process bulk and single cell ribo and RBP STAMP datasets
  force: false
  is_nfcore: true
  name: stamp
  org: nf-core
  outdir: .
  skip_features:
    - gpu
  version: 1.0.0dev
